import './globals.css';
import { Inter } from 'next/font/google';

import GoogleAnalytics from '@/scripts/GoogleAnalytics';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <GoogleAnalytics trackingId={process.env.GOOGLE_ANALYTICS_TRACKING_ID} />
    </html>
  );
}
